# Generated by Django 4.2.2 on 2023-06-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_univesity'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='leaderimage',
            field=models.ImageField(blank=True, upload_to='leader'),
        ),
        migrations.AddField(
            model_name='univesity',
            name='leaderimage',
            field=models.ImageField(blank=True, upload_to='leader'),
        ),
    ]
