# Generated by Django 4.0.6 on 2023-06-30 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0006_alter_events_date'),
        ('colleges', '0007_alter_news_date'),
    ]

    operations = [
    ]
