# Generated by Django 4.0.6 on 2023-06-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0008_merge_0006_alter_events_date_0007_alter_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
