# Generated by Django 4.2.2 on 2023-07-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0009_alter_news_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('contact_number', models.CharField(max_length=14)),
                ('leader', models.CharField(max_length=30)),
                ('leader_image', models.ImageField(null=True, upload_to='')),
                ('about', models.TextField()),
            ],
        ),
    ]
