# Generated by Django 4.2.2 on 2023-07-03 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0010_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='college',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='colleges.college'),
            preserve_default=False,
        ),
    ]
