# Generated by Django 4.2.2 on 2023-07-03 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0011_office_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='leader',
        ),
        migrations.RemoveField(
            model_name='office',
            name='leader_image',
        ),
        migrations.CreateModel(
            name='Staffmember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('academicRank', models.CharField(max_length=255)),
                ('startingDate', models.DateField()),
                ('educationAttended', models.TextField()),
                ('email', models.EmailField(max_length=255)),
                ('contact_number', models.CharField(max_length=14)),
                ('leader', models.CharField(max_length=30)),
                ('image', models.ImageField(null=True, upload_to='leader')),
                ('Office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.office')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.department')),
            ],
        ),
    ]
