# Generated by Django 4.2.2 on 2023-07-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0012_remove_office_leader_remove_office_leader_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='academicRank',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='contact_number',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='educationAttended',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='leader',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='startingDate',
            field=models.DateField(blank=True),
        ),
    ]
