# Generated by Django 4.2.2 on 2023-07-04 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0013_alter_staffmember_academicrank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmember',
            name='Office',
        ),
    ]
