# Generated by Django 4.2.2 on 2023-07-04 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0014_remove_staffmember_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='leaderuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='colleges.staffmember'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='office',
            name='staffmembers',
            field=models.ManyToManyField(related_name='members', to='colleges.staffmember'),
        ),
    ]
