# Generated by Django 4.2.2 on 2023-07-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0015_office_leaderuser_office_staffmembers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='facilities')),
            ],
        ),
        migrations.RenameField(
            model_name='staffmember',
            old_name='leader',
            new_name='leader_role',
        ),
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.CharField(choices=[('Comanadnt Office', 'Comanadnt Office'), ('ForeignREaltionOffice', 'ForeignREaltionOffice'), ('Acadamicoffice', 'Acadamicoffice'), ('QualityAssuranceOffice', 'QualityAssuranceOffice'), ('PostGraduaationOffice', 'PostGraduaationOffice'), ('RegistralOffice', 'RegistralOffice'), ('logesticsAndHousingOffice', 'logesticsAndHousingOffice'), ('law Office', 'law Office'), ('StudentCouncleOffice', 'StudentCouncleOffice'), ('OfficeOfhumanResource', 'OfficeOfhumanResource'), ('OfficeOfsecurity', 'OfficeOfsecurity')], default='Acadamicoffice', max_length=63),
        ),
    ]
