# Generated by Django 4.2.2 on 2023-07-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0016_gallery_rename_leader_staffmember_leader_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.CharField(choices=[('Comanadnt Office', 'Comanadnt Office'), ('ForeignREaltionOffice', 'ForeignREaltionOffice'), ('Acadamicoffice', 'Acadamicoffice'), ('QualityAssuranceOffice', 'QualityAssuranceOffice'), ('PostGraduaationOffice', 'PostGraduaationOffice'), ('RegistralOffice', 'RegistralOffice'), ('logesticsAndHousingOffice', 'logesticsAndHousingOffice'), ('law Office', 'law Office'), ('StudentCouncleOffice', 'StudentCouncleOffice'), ('OfficeOfhumanResource', 'OfficeOfhumanResource'), ('OfficeOfsecurity', 'OfficeOfsecurity')], default='Acadamicoffice', max_length=30),
        ),
    ]
