# Generated by Django 4.2.2 on 2023-07-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0017_alter_office_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.CharField(choices=[('Commandant Office', 'Commandant Office'), ('Foreign Relation Office', 'Foreign Relation Office'), ('Academic Office', 'Academic Office'), ('Quality Assurance Office', 'Quality Assurance Office'), ('Post Graduation Office', 'Post Graduation Office'), ('Registrar Office', 'Registrar Office'), ('Logistics and Housing Office', 'Logistics and Housing Office'), ('Law Office', 'Law Office'), ('Student Council Office', 'Student Council Office'), ('Office of Human Resource', 'Office of Human Resource'), ('Office of Security', 'Office of Security')], default='Academic Office', max_length=30),
        ),
    ]
