# Generated by Django 4.2.2 on 2023-07-04 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0018_alter_office_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='office',
            unique_together={('name', 'college')},
        ),
    ]
