# Generated by Django 4.2.2 on 2023-07-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0019_alter_office_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='biography',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='facebooklink',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='linkedin',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='researchInterest',
            field=models.TextField(null=True),
        ),
    ]
